#!/bin/bash
# Script to generate expected output VCFs for regression testing
# Run from repo root via WSL

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

echo "Working from: $REPO_ROOT"

# Check tools
echo "bcftools: $(bcftools --version 2>&1 | head -1)"
echo "bedtools: $(bedtools --version 2>&1 | head -1)"

REF_FASTA="tests/data/synthetic/mini_ref.fa"
INCLUDE_BED="tests/data/include_regions.bed"
EXCLUDE_BED="tests/data/exclude_regions.bed"
GENOME="tests/data/hg19_chr22.genome"
EXPECTED_DIR="tests/data/expected"

mkdir -p "$EXPECTED_DIR"

# Record baseline commit
COMMIT=$(git rev-parse HEAD)
DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)
VERSION=$(grep '^version=' hardnormly.sh | head -1)

{
    echo "# Generated by hardnormly.sh at commit: ${COMMIT}"
    echo "# Date: ${DATE}"
    echo "# hardnormly.sh ${VERSION}"
    echo "# Reference: ${REF_FASTA}"
} > "${EXPECTED_DIR}/BASELINE.txt"

echo "Wrote baseline header to BASELINE.txt"

# Run GATK samples
for SAMPLE in A B; do
    echo "Running GATK sample ${SAMPLE}..."
    ./hardnormly.sh \
        -v "tests/data/synthetic/gatk_sample_${SAMPLE}.vcf.gz" \
        -f "${REF_FASTA}" \
        -b "${INCLUDE_BED}" \
        -e "${EXCLUDE_BED}" \
        --filters-file defaults/gatk_filters.txt \
        -g "${GENOME}" \
        -o "${EXPECTED_DIR}/gatk_sample_${SAMPLE}_filtered.vcf.gz" \
        --auto-index
    echo "Done: gatk_sample_${SAMPLE}_filtered.vcf.gz"
done

# Run Freebayes samples
for SAMPLE in A B; do
    echo "Running Freebayes sample ${SAMPLE}..."
    ./hardnormly.sh \
        -v "tests/data/synthetic/freebayes_sample_${SAMPLE}.vcf.gz" \
        -f "${REF_FASTA}" \
        -b "${INCLUDE_BED}" \
        -e "${EXCLUDE_BED}" \
        --filters-file defaults/freebayes_filters.txt \
        -g "${GENOME}" \
        -o "${EXPECTED_DIR}/freebayes_sample_${SAMPLE}_filtered.vcf.gz" \
        --auto-index
    echo "Done: freebayes_sample_${SAMPLE}_filtered.vcf.gz"
done

echo ""
echo "=== Validation ==="
for vcf in "${EXPECTED_DIR}"/*_filtered.vcf.gz; do
    echo "--- $vcf ---"
    bcftools view "$vcf" -Oz -o /dev/null && echo "  Format: OK"
    echo "  Records: $(bcftools view -H "$vcf" | wc -l)"
    echo "  Filters:"
    bcftools query -f '%FILTER\n' "$vcf" | sort | uniq -c
done

echo ""
echo "=== Recording per-variant filter summaries ==="

{
    echo ""
    echo "# Per-variant filter results:"
    echo ""

    for CALLER in gatk freebayes; do
        for SAMPLE in A B; do
            VCF="${EXPECTED_DIR}/${CALLER}_sample_${SAMPLE}_filtered.vcf.gz"
            echo "# ${CALLER} sample ${SAMPLE}:"
            bcftools query -f '%CHROM\t%POS\t%FILTER\n' "$VCF"
            echo ""
        done
    done
} >> "${EXPECTED_DIR}/BASELINE.txt"

echo "BASELINE.txt updated with per-variant filter summaries."
echo ""
echo "=== Done ==="
