hardnormly_script: "./hardnormly.sh"
reference_fasta: "ref/hs37d5.fa"
include_beds:
  - "ref/target_files/agilent/S07604514/hg19/S07604514_Regions_hg19_valid_nochr.bed"
  - "ref/target_files/idt/hg19/IDT_xGen_Research_Targets_V1_hg19_nochr.bed"
exclude_beds:
  - "ref/exclude_files/dukeExcludeRegions.bed"
  - "ref/exclude_files/consensusBlacklist.bed"
filters_file: "defaults/filters.txt"
genome_file: "defaults/hg19.genome"
output_dir: "/data/cephfs-1/work/projects/nephrology-exomes/2024-01-19_stoneformer-exomes/Exomiser/exomiser-cli-14.0.0/vcf/hardnormly/"